# Generated by Django 3.2.6 on 2022-02-13 17:10

from django.db import migrations
from django.db.models import Q


def copy_destinations_to_phone_number(apps, schema_editor):
    PhoneNumber = apps.get_model("argus_auth", "PhoneNumber")
    DestinationConfig = apps.get_model("argus_notificationprofile", "DestinationConfig")
    db_alias = schema_editor.connection.alias

    for destination in DestinationConfig.objects.filter(media__slug="sms"):
        PhoneNumber.objects.using(db_alias).get_or_create(
            user=destination.user,
            phone_number=destination.settings["phone_number"],
        )


def copy_destinations_to_media_v1(apps, schema_editor):
    NotificationProfile = apps.get_model("argus_notificationprofile", "NotificationProfile")

    for profile in NotificationProfile.objects.all():
        if (
            profile.destinations.filter(media__slug="email").exists()
            and profile.destinations.filter(media__slug="sms").exists()
        ):
            profile.media_v1 = ["EM", "SM"]
        elif profile.destinations.filter(media__slug="email").exists():
            profile.media_v1 = ["EM"]
        elif profile.destinations.filter(media__slug="sms").exists():
            profile.media_v1 = ["SM"]
        profile.save(update_fields=["media_v1"])


def link_phone_numbers_with_notification_profiles(apps, schema_editor):
    PhoneNumber = apps.get_model("argus_auth", "PhoneNumber")
    NotificationProfile = apps.get_model("argus_notificationprofile", "NotificationProfile")
    db_alias = schema_editor.connection.alias

    changed_profiles = []
    for profile in NotificationProfile.objects.filter(destinations__media__slug="sms"):
        phone_number = profile.destinations.filter(media__slug="sms").order_by("pk")[0].settings["phone_number"]
        profile.phone_number = PhoneNumber.objects.using(db_alias).get(
            Q(user=profile.user) & Q(phone_number=phone_number)
        )
        changed_profiles.append(profile)
    if changed_profiles:
        NotificationProfile.objects.bulk_update(changed_profiles, ["phone_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("argus_notificationprofile", "0005_destinationconfig_media"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, link_phone_numbers_with_notification_profiles),
        migrations.RunPython(migrations.RunPython.noop, copy_destinations_to_media_v1),
        migrations.RunPython(migrations.RunPython.noop, copy_destinations_to_phone_number),
    ]
